FROM --platform=$BUILDPLATFORM golang:1.27-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG COMMIT=unknown
ARG DATE=unknown

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath \
      -ldflags="-s -w -X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}" \
      -o /out/md2confluence ./cmd/md2confluence

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/md2confluence /usr/local/bin/md2confluence
USER nonroot:nonroot
WORKDIR /work
ENTRYPOINT ["/usr/local/bin/md2confluence"]
